import psycopg2.extras
import json
import requests

conn = psycopg2.connect(host='pg.pg4e.com',
        port=5432,
        database='pg4e_d2be0b613b', 
        user='pg4e_d2be0b613b', 
        password='pg4e_p_4ea940f9b57cdb5', 
        connect_timeout=3)
cur = conn.cursor()



defaulturl = 'https://pokeapi.co/api/v2/pokemon?limit=100&offset=0'

sql = 'CREATE TABLE IF NOT EXISTS pokeapi("id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, body JSONB);' 
print(sql)
cur.execute(sql)

response = requests.get(defaulturl)
js = json.loads(response.text)

results = js['results']# js is a library and i'm interested in the values of 'results' key.
rows = list()
# 'results' is a list of libraries and i want to loop through each element of the list
# and extract the value of 'url' key
# I NEED TO INSERT EACH VALUE INTO pokeapi (body), note that 'body' is of type JSONB

for result in results:
    response = requests.get(result['url'])
    rows.append([response.text])
    sql = 'INSERT INTO pokeapi (body) VALUES %s;'
    cur.execute(sql, [defaulturl, ])

print('Closing database connection...')
conn.commit()
cur.close() 
